name: Docker images CI
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  image:
    name: JDK-${{ matrix.java }}, ${{ matrix.image_base }} ${{ matrix.pulsar_style == 'true' && ' (pulsar style)' || '' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image_base: ['debian:bookworm', 'ubuntu:22.04']
        java: ['8', '11', '17', '21']
        pulsar_style: ['false', 'true']

    steps:
      - uses: actions/checkout@v3

      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile${{ matrix.pulsar_style == 'true' && '-pulsar' || '' }}
          context: .
          build-args: |
            IMAGE_BASE=${{ matrix.image_base }}
            JAVA=${{ matrix.java }}
