name: Docker images CI
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  image:
    name: Termurin ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: ['8', '11', '17', '21']

    steps:
      - uses: actions/checkout@v3

      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          context: .
          build-args: JAVA=${{ matrix.java }}

  image_pulsar:
    name: Termurin ${{ matrix.java }} (pulsar style)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: ['8', '11', '17', '21']

    steps:
      - uses: actions/checkout@v3

      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile-pulsar
          context: .
          build-args: JAVA=${{ matrix.java }}
