name: Docker images CI
on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  image:
    name: Termurin ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: ['8', '11', '17', '21']

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          file: Dockerfile
          context: .
          push: false
          build-args: |
            JAVA=${{ matrix.java }}
